### ISSUE TITLE
Please add ability to monitor Microsoft-Windows-IIS-Logging-Logs

### ISSUE THREAD

**Issue by artisticcheese** [Ticketmaster/spinner#4]
You can make IIS to log to ETW and then consume in log above. This has certain advantages over `tail` of physical file

1. Location is always the same so no change of spinner exiting because it's just not there or location changed
2. Automatic size maintenance of log (no need for log cleanup etc)
3. I would assume probably better performance since it's ETW and not constantly pulling file from disk

**Comment by cdhunt** [comment]
@artisticcheese, Thanks for the suggestion. That makes a lot of sense, however, this is probably not a feature we'll be able to implement anytime soon. We haven't been able to find any existing libraries that provide that type of interface to ETW. Writing a new Go library is more work than we can commit to at the moment. I'll leave the issue open, but I can't provide an ETA.

**Comment by artisticcheese** [comment]
Well instead of subscribing to ETW events you can just pull EventLog instead, this will not require any ETW API use just use for EventLog API.

**Comment by cdhunt** [comment]
We might be able to use https://github.com/elastic/beats/blob/master/winlogbeat/eventlog/wineventlog.go.

**Comment by artisticcheese** [comment]
@cdhunt That library looks like for Event Logs, the one IIS writes to is ETW channel which is consumed by Event Log stored under "Application and Services Log" which looks like is separate entity from Windows Event Logs
